name: Test, Build and Publish a beta version

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint, build, test and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY_SKIP_INSTALL: true
        run: |
          npm run lint
          npm run build
          # npm run test
          npx semantic-release --debug
